version: '3.9'

services:
  db:
    image: postgres:10.5
    volumes:
      - ./data/db:/var/lib/postgresql/data
    environment:
      - POSTGRES_DB=djangochat
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
  
  web:
    build: .
    command: python /code/djangochat/manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/code
    ports:
      - "8000:8000"
    environment:
      - POSTGRES_DB=djangochat
      - POSTGRES_USER=user
      - PSOTGRES_PASSWORD=password
    depends_on:
      - db